#Configuration for ccLoadBalancer
config: 
  - name: primary
    listenAddr: localhost:8080
    algorithm: roundrobin
    endpoints:
      - localhost:8081
      - localhost:8082
  - name: secondary
    listenAddr: localhost:8000
    algorithm: leastconnection
    endpoints:
      - localhost:8001
      - localhost:8002
  - name: tertiary
    listenAddr: localhost:8085
    algorithm: iphash
    endpoints:
      - localhost:8003
